version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: poker-tracker-db
    environment:
      POSTGRES_DB: PokerTrackerDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database-init.sql:/docker-entrypoint-initdb.d/database-init.sql
    networks:
      - poker-tracker-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin Web Interface
  pgadmin:
    image: dpage/pgadmin4
    container_name: poker-tracker-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      # Pre-configure the PostgreSQL server connection
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json
      - ./pgpass:/pgpass
    depends_on:
      - postgres
    networks:
      - poker-tracker-network

  # .NET Core API
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: poker-tracker-api
    ports:
      - "5000:80"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=PokerTrackerDb;Username=postgres;Password=yourpassword
      - JWT__ValidAudience=http://localhost:3000
      - JWT__ValidIssuer=http://localhost:5000
      - JWT__Secret=1D9y$58aF3@kL7*pQ2!wXzB6^mR4#vS8gT1h&jE9cN5bV0uP
    networks:
      - poker-tracker-network

networks:
  poker-tracker-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
